### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by helder-garcia**
Walletd not using checkpoint and others

### CODE REVIEW

**Comment by aivve** [comment]
Too many files and commits. 😨

**Comment by helder-garcia** [comment]
yes kkk. you better cherry pick https://github.com/niobio-cash/niobio-node-daemon/commit/791e631dc066dfb1fcb53b1d44fc42a7e22b90a3

**Comment by aivve** [comment]
If it's about orphan status we already have something like this. I will check if we have it everywhere you added.

**Comment by helder-garcia** [comment]
No, it's the "walletd not using checkpoints" commit. The orphan status I took from you. I was comparing the code trying to find some reason to my RPC server stucks from time to time. I found this, not related, but useful and included it in my code.

**Comment by aivve** [comment]
Thanks but we already have this orphan status.  Ah, thanks to you noticed and removed duplicate value.
Aldeady cherry picked checkpoints for walletd.  👍

**Comment by helder-garcia** [comment]
Just saw you've already pushed it!

**Pull request closed without merging**
