### PR TITLE
Added mnemonic-seed-file command line

### PR DESCRIPTION
**Pull request by Lastick**

### CODE REVIEW

**Comment by aivve** [comment]
@Lastick, do you need to dump only seed? Because we have a function to dump raw keys + mnemonic to file already, we can hook it also for a command-line flag.

Besides the mnemonic seed formatting doesn't allow to import seed to some wallets, need to remove spaces. AFAIR in browser wallet.

**Comment by aivve** [comment]
@Lastick so you want to add option to dump keys / mnemonic during the creation of a new wallet via flags?

**Comment by Lastick** [comment]
Yes, aivve

**Comment by aivve** [comment]
> Yes, aivve

Got it, I restored your original behavior (not exactly as you did it but it allows saving only mnemonic during wallet creation) in 5a23f49d8810271771432f15aaa64543e9244e2d. Bear in mind that I shortened the flag to `mnemonic-file`

**Pull request merged**
