### PR TITLE
Peersmap

### PR DESCRIPTION
**Pull request by vitorgamer58**
these modifications allow you to map pairs with a lot more pairs, normally our coins have a limit of 1000 White pairs and 5000 Gray Pairs, so I made a UP for 10000 White peers, and the number of gray peers I left static. I made the same pull request on Niobio_Cash https://github.com/niobio-cash/niobio-node-daemon/pull/21
peers nbr
karbo peers
these KRB peers are from my daemon that went live yesterday, so there are few peers

### CODE REVIEW

**Comment by aivve** [comment]
Hi, thanks but I'm overhelmed with all those commits. Better PR map script with fixes 👍

**Comment by vitorgamer58** [comment]
well, this is not a very important subject, then you take a look after

**Comment by aivve** [comment]
I see the changes, thank you. Maybe we will build special version of the node with such a big list. Can you pull request to the map script with fixes?

**Comment by vitorgamer58** [comment]
I'm going to tell you ... kkkk, I thought I had fixed the problem but ... I did not correct it, if the map refreshes quickly to show everyone without being bugged it needs to pull the location many times by freegeoip, even if it only allows 10 thousand every hour, needing to open its own freegeoip (in the same machine) for this, we would need to think of a form of the code to get the locations, show on the map even if it has many users seeing, and only need to request the locations 1 or 2 hours later.

**Pull request closed without merging**
