### PR TITLE
Fix MacOS build (HttpClient.cpp)

### PR DESCRIPTION
**Pull request by Lastick**
My girlfriend helped again :)

### CODE REVIEW

**Comment by aivve** [comment]
Yes, thanks. Already have done this for [Karbo 2](https://github.com/Karbovanets/karbo/pull/39/commits/45922acad5359e822a5ddc4584d70a5d635faea5).

**Comment by baytuch** [comment]
Karbo release for Rasberry PI 3 (Debian Stretch):
https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.tar.gz
https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.zip

compiled by human, but not soulless machine :)

**Comment by Lastick** [comment]
Karbo release for Rasberry PI 3 (Debian Stretch):
https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.tar.gz
https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.zip

compiled by human, but not soulless machine :)

**Comment by Lastick** [comment]
https://github.com/seredat/karbowanec/pull/159#issuecomment-933190260

**Comment by aivve** [comment]
> 
> 
> Karbo release for Rasberry PI 3 (Debian Stretch): https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.tar.gz https://karbo-labs.pp.ua/tmp/karbo/karbowanec-stretch-1.8.2_linux_ARMv7.zip
> 
> compiled by human, but not soulless machine :)

Ty, could you publish your mod for nginx nodes proxy balancer? Need to update OS on servers.

**Pull request merged**
