### PR TITLE
checked double bug. ok. this make 2nd key track

### PR DESCRIPTION
**Pull request by SoraKohaku**
fixed bug

### CODE REVIEW

**Comment by aivve** [comment]
Already aware. It doesn't matter since size is the same. But thanks!

**Comment by SoraKohaku** [comment]
no problem cuz this same as us. thank for share. and you did great. the problem about simple wallet. we wanna make rich list how about that?same here

**Comment by aivve** [comment]
Rich list in cryptonote? Don't do that :)

**Comment by SoraKohaku** [comment]
ok then skip ahaha

**Pull request merged**
